name: flutter_platform_alert
version: 0.6.0
homepage: https://github.com/zonble/flutter_platform_alert
description: A plugin helps to call native API to play alert sound and show alert dialogs. For example, it bridges MessageBox and TaskDialogIndirect on Windows.
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"
dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ">=1.0.0 <5.0.0"
  import_sorter: 4.6.0
  pubspec_dependency_sorter: 1.0.5
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: net.zonble.flutter_platform_alert
        pluginClass: FlutterPlatformAlertPlugin
      ios:
        pluginClass: FlutterPlatformAlertPlugin
      macos:
        pluginClass: FlutterPlatformAlertPlugin
      windows:
        pluginClass: FlutterPlatformAlertPlugin
      linux:
        pluginClass: FlutterPlatformAlertPlugin
import_sorter:
  emojis: false
  comments: false
screenshots:
  - description: flutter_platform_alert on Android
    path: screenshot_android.png
  - description: flutter_platform_alert on iOS
    path: screenshot_ios.png
  - description: flutter_platform_alert sheet on iOS
    path: screenshot_ios_sheet.png
  - description: flutter_platform_alert on Linux.
    path: screenshot_linux.png
  - description: flutter_platform_alert on macOS.
    path: screenshot_macos.png
  - description: flutter_platform_alert on Windows.
    path: screenshot_windows.png
  - description: flutter_platform_alert on Windows 11.
    path: screenshot_windows_11.png
